# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param project.vivado.isBlockSynthRun true
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/USER/Desktop/Stepper_Motor_Full_Step/Stepper_Motor_Full_Step.cache/wt [current_project]
set_property parent.project_path D:/USER/Desktop/Stepper_Motor_Full_Step/Stepper_Motor_Full_Step.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{d:/USER/Desktop/羅設實驗1/新增資料夾/Keyboard Sample Code/Keyboard Sample Code/ip}} [current_project]
update_ip_catalog
set_property ip_cache_permissions disable [current_project]
read_ip -quiet d:/USER/Desktop/Stepper_Motor_Full_Step/Stepper_Motor_Full_Step.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top KeyboardCtrl_0 -part xc7a35tcpg236-1 -mode out_of_context

rename_ref -prefix_all KeyboardCtrl_0_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef KeyboardCtrl_0.dcp
create_report "KeyboardCtrl_0_synth_1_synth_report_utilization_0" "report_utilization -file KeyboardCtrl_0_utilization_synth.rpt -pb KeyboardCtrl_0_utilization_synth.pb"

if { [catch {
  file copy -force D:/USER/Desktop/Stepper_Motor_Full_Step/Stepper_Motor_Full_Step.runs/KeyboardCtrl_0_synth_1/KeyboardCtrl_0.dcp d:/USER/Desktop/Stepper_Motor_Full_Step/Stepper_Motor_Full_Step.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub d:/USER/Desktop/Stepper_Motor_Full_Step/Stepper_Motor_Full_Step.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub d:/USER/Desktop/Stepper_Motor_Full_Step/Stepper_Motor_Full_Step.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim d:/USER/Desktop/Stepper_Motor_Full_Step/Stepper_Motor_Full_Step.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim d:/USER/Desktop/Stepper_Motor_Full_Step/Stepper_Motor_Full_Step.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir D:/USER/Desktop/Stepper_Motor_Full_Step/Stepper_Motor_Full_Step.ip_user_files/ip/KeyboardCtrl_0]} {
  catch { 
    file copy -force d:/USER/Desktop/Stepper_Motor_Full_Step/Stepper_Motor_Full_Step.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0_stub.v D:/USER/Desktop/Stepper_Motor_Full_Step/Stepper_Motor_Full_Step.ip_user_files/ip/KeyboardCtrl_0
  }
}

if {[file isdir D:/USER/Desktop/Stepper_Motor_Full_Step/Stepper_Motor_Full_Step.ip_user_files/ip/KeyboardCtrl_0]} {
  catch { 
    file copy -force d:/USER/Desktop/Stepper_Motor_Full_Step/Stepper_Motor_Full_Step.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0_stub.vhdl D:/USER/Desktop/Stepper_Motor_Full_Step/Stepper_Motor_Full_Step.ip_user_files/ip/KeyboardCtrl_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
